---
scram_num_pairs:      3
scram_num_tasks:      3
scram_max_hint_level: 2
scram_t2_price:    1.00
scram_t2_volume:   10
scram_t1_price:    1.00
scram_t1_volume:   20
scram_t0_price:    1.00
scram_t0_volume:   30
scram_p2_price:    1.00
scram_p2_volume:   20
scram_p1_price:    1.00
scram_p1_volume:   40
scram_p0_price:    1.00
scram_p0_volume:   60
