---
tracker_type: github
tracker_name: bugmark/bugmark_docs
# webapp_url: scramword.bugmark.net:4567
# tracker_type: yaml
# tracker_name: /tmp/scramword.yml
webapp_url:   soak:4567
base_price:    1.00
base_volume:   10
start_date: 2018-05-02
finish_date: 2018-05-04
leader_name: Malvika Rao
leader_email: malvikar@gmail.com
participants:
  - andy@r210.com
  - malvikar@gmail.com
  - linkgeorg@gmail.com
  - dmarti@mozilla.com
  - sstruble@mozilla.com

