---
webapp_url:   exercise.bugmark.net:4567
tracker_type: github
tracker_name: bugmark/bugmark_docs
# webapp_url:       soak:4567
# tracker_type:     yaml
# tracker_name:     /tmp/worker.yml
repo_url:     github.com/bugmark/bugmark_docs 
start_date:   2018-05-14
finish_date:  2018-05-17
funder_email: malvikar@gmail.com
leader_name:  Malvika Rao
leader_email: malvikar@gmail.com
scram_c3_volume: 20
scram_c2_volume: 20
scram_c1_volume: 20
scram_c0_volume: 20
scram_p3_volume: 20
scram_p2_volume: 20
scram_p1_volume: 20
scram_p0_volume: 20
participants:
  - andy@r210.com
  - linkgeorg@gmail.com
  - sstruble@mozilla.com
  - richbodo@gmail.com
  - dmarti@mozilla.com
  - carlos.arad@yahoo.de
  - enrique.86@gmail.com
  - nikhil.hassija@gmail.com
  - tomica@gmail.com
  - harakiscbacharakis@mozilla.com
  - aabid@unomaha.edu
  - s@goggins.com
  - punya.viswanath@gmail.com
  - snehasin1997@gmail.com
  - robertweber95@gmail.com
  - jandrianatoandro@unomaha.edu 

